### ISSUE TITLE
Certificate of Completion for Sahaja

### ISSUE THREAD

**Issue by srija-ieee** [ayeinterns/ayeinterns-winter2021#3]
Dear Sahaja, 

Congratulations on completing a three month long winter internship with AyeAI Consulting, on Project VIKRAM from December 2021 to February 2022! We have thoroughly enjoyed working with you and are proud to have you among our alumni. 

We thank you for the effort and appreciate your perseverance and dedication to the tasks assigned. You have demonstrated a very good ability to grasp new concepts and have been good at working with remote working methods, maintaining perfect availability and responsiveness. 

We believe the exposure to concepts of 3D Modeling in light of building a virtual model for various scenarios of VKC Education services (for AyeATROS micro entrepreneurs), will give you a foundation in intuitive illustration of a concept.  We expect you will continue to build further depth in the topics 
learnt in correlation with your studies and coursework. 

We look forward to your continued interest in the domain and participation in various open source projects including those from other verticals of AyeAI. We also invite you to participate in our Campus Ambassadors Program (AyeCAP) wherein you can help spread awareness of Project VIKRAM among your friends and colleagues. 

We would like to gently remind you of standing obligations with regards to intellectual property as accepted during initial documentation; whereas, all due diligence have been exercised in engaging you only in IP neutral open source projects, Notwithstanding, given the complex nature of technical environments, there may have been inadvertent exposure to some proprietary material or official secrets such as, and Not limited to, product or service roadmaps, undisclosed inventions, unpublished material or other intellectual property and, Therefore, we would advise you to keep us informed and consult with our legal advisors in case you are involved in projects similar to the AyeAI offerings in the near future till a period of two years from the date of completion of your latest internship, employment, or other engagement with us. We would also like to mention that any usage of the AyeAI trademark, or affiliated organizations' logos, trademarks, copyrighted material, or any other intellectual property requires explicit permission from the respective company leadership. We will be happy to provide you appropriate certificates and references related to the work done. For all official communications please use the contact links available from our website with your AyeAI Unique ID which shall be communicated to you shortly. Kindly do not expose any Identifiable or Sensitive Personal Information (ISPI) on public platforms and share those only over secure and private channels. You are encouraged to actively bring to our notice any issues with legal and compliance that you encounter in the future related to your engagement with us. 

This letter marks the full and final closure of the current engagement with AyeAI Consulting, with no further dues or actionable items remaining pending on either party. There is no objection to your participation in any other internship or employment hereafter. 

Wishing you all the very best in your academics and looking forward to having you in the AyeCAP program. 

Regards,
Dr Srija Katta
Co-Founder - AyeAI
 
PS: The pull request is approved pertaining to review by legal team prior to inclusion in any AyeAI deliverable. 

Note: Valid only when committed under the official account of the author. No warranties or fitness is guaranteed on the deliverables. The content has not been endorsed and the original committing authors are solely responsible for ensuring no intellectual property have been infringed. Accepted in good faith only.

**Comment by obonac** [comment]
Original pull request ayeinterns/ayeinterns-winter2021/pull/1

**Comment by obonac** [comment]
Proof of work for verification:
Original pull request ayeinterns/ayeinterns-winter2021/pull/1
Merge commit https://github.com/ayeinterns/ayeinterns-winter2021/commit/6cee2caedddb7a2cd4557614e6267a97db91a534

Work portfolio for validation:
AyeInterns Portfolio https://ayeinterns.github.io/ayeinterns-winter2021/sahaja/3js/
AyePages Escrow http://web.archive.org/web/20220326072456/https://sahajaportfolio.github.io/

**Comment by obonac** [comment]
http://web.archive.org/web/20220329005720/https://github.com/ayeinterns/ayeinterns-winter2021/issues/3

**Comment by obonac** [comment]
Escrowed link to issue http://web.archive.org/web/20220329005720/https://github.com/ayeinterns/ayeinterns-winter2021/issues/3

**Comment by obonac** [comment]
Proof of work escrowed http://web.archive.org/web/20220329010053/https://github.com/ayeinterns/ayeinterns-winter2021/pull/1

**Comment by obonac** [comment]
Portfolio escrowed http://web.archive.org/web/20220329023948/https://ayeinterns.github.io/ayeinterns-winter2021/sahaja/3js/

**Comment by obonac** [comment]
Correction to original information in pull request tallied with records.
Update confirmation escrowed at http://web.archive.org/web/20220329074534/https://github.com/ayeinterns/ayeinterns-winter2021/pull/1

**Comment by obonac** [comment]
Proof of work escrowed http://web.archive.org/web/20220329010053/https://github.com/ayeinterns/ayeinterns-winter2021/pull/1
Portfolio escrowed http://web.archive.org/web/20220329023948/https://ayeinterns.github.io/ayeinterns-winter2021/sahaja/3js/

Certification escrowed http://web.archive.org/web/20220329005720/https://github.com/ayeinterns/ayeinterns-winter2021/issues/3
Correction to original information in pull request tallied with records.
Update confirmation escrowed at http://web.archive.org/web/20220329074534/https://github.com/ayeinterns/ayeinterns-winter2021/pull/1

**Comment by obonac** [comment]
Certification completed with commit https://github.com/ayeinterns/ayeinterns-winter2021/commit/8fd799d783046d8f1e15b630d8447017130daa0a
